#!/bin/bash

IMG_PATH="../disk/test_disk.img"

LOOP_DEVICE=$(losetup -a | grep "$IMG_PATH" | awk -F: '{print $1}')

if [ -n "$LOOP_DEVICE" ]; then
  echo "Detaching loop device $LOOP_DEVICE"
  sudo losetup -d "$LOOP_DEVICE"
fi

if [ ! -f "$IMG_PATH" ]; then
  echo "Disk already removed"
  exit 0
fi

echo "Removing test disk image at $IMG_PATH"
rm "$IMG_PATH"
